# values-dev/values.yaml

service:
  type: NodePort
  port: 80

wordpress:
  env:
    WORDPRESS_DATABASE_PASSWORD: Test@123

ingress:
  enabled: true
  hosts:
    - host: dev.example.com
      paths:
        - /