service:
  type: NodePort
  port: 8081
  targetPort: 8081   # Replace with your desired target port for dev

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: dev.my-app.local
      paths:
        - /
