# templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-kubernetes-chart.fullname" . }}
spec:
  selector:
    app: {{ include "hello-kubernetes-chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080