# values-test/values.yaml

service:
  type: ClusterIP
  port: 80

# values-dev/values.yaml and values-test/values.yaml
ingress:
  enabled: true
  hosts:
    - host: test.example.com
      paths:
        - /