service:
  type: NodePort
  port: 8082
  targetPort: 8082   # Replace with your desired target port for test

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: test.my-app.local
      paths:
        - /
