# values-test/values.yaml

service:
  type: ClusterIP
  port: 8082

# values-dev/values.yaml and values-test/values.yaml
ingress:
  enabled: true
  hosts:
    - host: test.my-app.local
      paths:
        - /