service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30802

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: test.my-app.local
      paths:
        - /