image:
  repository: amithack93/flask-docker
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""

fullnameOverride: ""

ingress:
  enabled: true
  hosts:
    - host: my-app.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80