# values.yaml

image:
  repository: amithack93/flask-docker
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: chart-app.local
      paths: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
# You can add more configuration options here as needed.
