# values.yaml

image:
  repository: bitnami/wordpress
  tag: latest
  pullPolicy: IfNotPresent

wordpress:
  env:
    ALLOW_EMPTY_PASSWORD: "yes"
    WORDPRESS_DATABASE_USER: "bn_wordpress"
    WORDPRESS_DATABASE_PASSWORD: "bitnami"
    WORDPRESS_DATABASE_NAME: "bitnami_wordpress"

volumes:
  - name: wordpress_data
    persistentVolumeClaim:
      claimName: wordpress-data

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
# You can add more configuration options here as needed.
